name: Build C++ Program

on:
  push:
    branches: [ "*" ]
  pull_request: 
    branches: [ "*" ]
  workflow_dispatch:
    branch: [ "*" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ./configure
        run: ./configure

      - name: make
        run: make

      - name: Run check
        run: make check

      - name: Run distcheck
        run: make distcheck

      - name: Log in to dokcerhub
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p {{ secrets.DOCKER_TOKEN }}

      - name: Build Dockerfile image
        run: docker build --platform=linux/amd64 -t markshulyhin/funcaserv --push .
        
        
