name: Build and Push Docker Image

on:
  push:
    branches: [ "branchHTTPserver" ]
  pull_request: 
    branches: [ "branchHTTPserver" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: QEMU install
        uses: docker/setup-qemu-action@v3
        
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: build ls
        run: docker buildx ls
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build Dockerfile image (amd64)
        run: docker build --platform linux/amd64 -t markshulyhin/funcaserv:amd64 --push -f /Dockerfile .
        
      - name: Build Dockerfile image(arm64)
        run: docker build --platform=linux/arm64 -t markshulyhin/funcaserv:arm64 --push -f /Dockerfile .
        
      - name: Manifest
        run: docker manifest create markshulyhin/funcaserv --amend markshulyhin/funcaserv:amd64 --amend markshulyhin/funcaserv:arm64
     
      - name: Push manifest
        run: docker manifest push markshulyhin/funcaserv
